export const shapes = [
  {
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  {
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  {
    width: 100,
    height: 100,
    borderRadius: 50,
    transform: [{scaleX: 2}],
    justifyContent: 'center',
    alignItems: 'center',
  },
  {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 50,
    borderRightWidth: 50,
    borderBottomWidth: 100,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  {
    width: 100,
    height: 100,
    transform: [{rotate: '45deg'}],
    justifyContent: 'center',
    alignItems: 'center',
  },
  {
    width: 126,
    height: 180,
    borderTopLeftRadius: 108,
    borderTopRightRadius: 108,
    borderBottomLeftRadius: 95,
    borderBottomRightRadius: 95,
    justifyContent: 'center',
    alignItems: 'center',
  },
];
